services:
  app:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always

  api:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: nonexist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
